# Test your FastAPI endpoints

###

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/plants
Accept: application/json

###

GET http://127.0.0.1:8000/plants/1
Accept: application/json

###

POST http://127.0.0.1:8000/plants/import
Accept: application/json

###

GET http://localhost:80/
Accept: application/json

###

GET http://localhost:80/plants
Accept: application/json

###

GET http://localhost:80/photo/123
Accept: application/json